export const projectCardDetails = [
  {
    id: "1",
    alt: "velcro whatsapp payment",
    image: "/velcro-dashboard.png",
    head: "Velcro",
    stack: "Nextjs",
    stack2: "Tailwindcss",
    stack3: "Typescript",
    parag: "A Whatsapp banking solution to receive payments via whatsapp.",
    code: "https://github.com/iconicconcept",
    live: "https://usevelcro.com",
    lock: "code",
    note: "Client project — code private under NDA",
  },
  {
    id: "2",
    alt: "Hospital system",
    image: "/omolewahms2.png",
    head: "Omolewa Hospital",
    stack: "Nextjs",
    stack2: "Zustand",
    stack3: "Typescript",
    parag: "An Hospital system for all the activities done in the hospital.",
    code: "https://github.com/iconicconcept",
    live: "https://omolewahospital.com",
    lock: "code",
    note: "Client project — code private under NDA",
  },
  {
    id: "4",
    alt: "criptpay",
    image: "/criptpay.png",
    head: "Criptpay",
    stack: "Nextjs",
    stack2: "Nodejs",
    stack3: "Typescript",
    parag: "A Crypto offramping platform.",
    code: "https://github.com/iconicconcept",
    live: "https://criptpay.com",
    lock: "code",
    note: "Client project — code private under NDA",
  },
  {
    id: "4",
    alt: "Formode portfolo",
    image: "/formode-dashboard.png",
    head: "Formode",
    stack: "Nextjs",
    stack2: "Expressjs",
    stack3: "Typescript",
    parag: "A portfolio website built for an architectural services firm.",
    code: "https://github.com/iconicconcept",
    live: "https://formode.ke",
    lock: "code",
    note: "Client project — code private under NDA",
  },
  {
    id: "5",
    alt: "estatein properties",
    image: "/stateproperties.png",
    head: "Estatein Properties",
    stack: "ReactJs",
    stack2: "Tailwindcss",
    stack3: "Javascript",
    parag: "A website built for an Estate Company.",
    code: "https://github.com/iconicconcept/Estatein-Properties.git",
    live: "https://estateinproperties.netlify.app",
  },
  {
    id: "6",
    alt: "e-commerce store",
    image: "/trackstore.png",
    head: "TrackStore",
    stack: "ReactJs",
    stack2: "NodeJs",
    stack3: "Tailwindcss",
    parag: "An E-commerce store for a fast fashion brand.",
    code: "https://github.com/iconicconcept/TrackStore.git",
    live: "https://trackstores.netlify.app",
  },
  // {
  //   id: "3",
  //   alt: "Forex Trading system",
  //   image: "/candleweb-dashboard.png",
  //   head: "Candleweb",
  //   stack: "Nextjs",
  //   stack2: "Zustand",
  //   stack3: "Typescript",
  //   parag: "A Forex Trading and AI automation teaching web application.",
  //   code: "https://github.com/iconicconcept",
  //   live: "https://candleweb.io",
  //   lock: "all",
  // },
  // {
  //   id: "8",
  //   alt: "expense tracker",
  //   image: "/followtrack.png",
  //   head: "FollowTrack",
  //   stack: "ReactJs",
  //   stack2: "Expressjs",
  //   stack3: "Typescript",
  //   parag:
  //     "An Expense tracker web app for effective expense and income tracking.",
  //   code: "https://github.com/iconicconcept/FollowTrack.git",
  //   live: "https://followtrack.onrender.com",
  // },
  // {
  //   id: "9",
  //   alt: "marketing agency web App",
  //   image: "/sqaureupagency.png",
  //   head: "SquareUp Agency",
  //   stack: "ReactJs",
  //   stack2: "Tailwindcss",
  //   stack3: "Typescript",
  //   parag: "A website built for a Marketing Agency Company.",
  //   code: "https://github.com/iconicconcept/SquareUp.git",
  //   live: "https://squareagency.netlify.app",
  // },
  // {
  //   id: "6",
  //   alt: "note taking web app",
  //   image: "/NOTE.png",
  //   head: "Note-It",
  //   stack: "ReactJs",
  //   stack2: "Tailwindcss",
  //   stack3: "Typescript",
  //   parag:
  //     "A Note taking application, it's use for taking Notes for future use",
  //   code: "https://github.com/iconicconcept",
  //   live: "https://noteit-Ifpq.onrender.com",
  // },
  // {
  //   id: "11",
  //   alt: "Team management",
  //   image: "/ManagingTeam.png",
  //   head: "Managing Team",
  //   stack: "HTML",
  //   stack2: "CSS",
  //   stack3: "Javascript",
  //   parag: "A website built for a team Management firm",
  //   code: "https://github.com/iconicconcept/managing-team.io.git",
  //   live: "https://iconicconcept.github.io/managing-team.io/",
  // },
  // {
  //     id: "8",
  //     alt: "deesmart store",
  //     image: "../smart.png",
  //     head: "DeeSmart Store",
  //     stack: "HTML",stack2: "CSS",stack3: "Javascript",
  //     parag: "A mini E-commerce web application, dedicated to making sales less stressful",
  //     code: "https://github.com/iconicconcept",
  //     live: "https://iconicconcept.github.io/deesmart-store/"
  // }
];

export const featureCard = [
  {
    id: "1",
    head: "Full-Stack Development",
    parag: "Building Responsive and scalable full-stack application",
  },
  {
    id: "2",
    head: "Web Application",
    parag:
      "Building Responsible and user-friendly web applications with modern Technologies",
  },
  {
    id: "3",
    head: "Problem Solving",
    parag: "Building solutions dedicated to solve complex technical challenges",
  },
  {
    id: "4",
    head: "Quality Performance",
    parag: "Solutions with quality performance and solving dedicated problems",
  },
  {
    id: "5",
    head: "SEO",
    parag: "Scalable solutions with great SEO",
  },
];
