export const projectCardDetails = [
  {
    id: "1",
    alt: "expense tracker",
    image: "/followtrack.png",
    head: "FollowTrack",
    stack: "ReactJs",
    stack2: "NodeJs",
    stack3: "Typescript",
    parag:
      "An Expense tracker web app for effective expense and income tracking",
    code: "https://github.com/iconicconcept",
    live: "https://followtrack.onrender.com",
  },
  {
    id: "2",
    alt: "e-commerce store",
    image: "/trackstore.png",
    head: "TrackStore",
    stack: "ReactJs",
    stack2: "NodeJs",
    stack3: "Tailwindcss",
    parag: "An E-commerce store for a fast fashion brand",
    code: "https://github.com/iconicconcept",
    live: "https://trackstores.netlify.app",
  },
  {
    id: "3",
    alt: "estatein properties",
    image: "/stateproperties.png",
    head: "Estatein Properties",
    stack: "ReactJs",
    stack2: "Tailwindcss",
    parag: "A website built for an Estate Company",
    code: "https://github.com/iconicconcept",
    live: "https://estateinproperties.netlify.app",
  },
  {
    id: "4",
    alt: "evently web app",
    image: "/Evently.png",
    head: "Eventley",
    stack: "ReactJs",
    stack2: "Tailwindcss",
    stack3: "Typescript",
    parag: "An event awareness web application, built for my school",
    code: "https://github.com/iconicconcept",
    live: "https://eventley.onrender.com",
  },
  {
    id: "5",
    alt: "marketing agency web App",
    image: "/sqaureupagency.png",
    head: "SquareUp",
    stack: "ReactJs",
    stack2: "Tailwindcss",
    stack3: "Typescript",
    parag: "A website built for a Marketing Agency Company",
    code: "https://github.com/iconicconcept",
    live: "https://squareagency.netlify.app",
  },
  // {
  //   id: "6",
  //   alt: "note taking web app",
  //   image: "/NOTE.png",
  //   head: "Note-It",
  //   stack: "ReactJs",
  //   stack2: "Tailwindcss",
  //   stack3: "Typescript",
  //   parag:
  //     "A Note taking application, it's use for taking Notes for future use",
  //   code: "https://github.com/iconicconcept",
  //   live: "https://noteit-Ifpq.onrender.com",
  // },
  {
    id: "6",
    alt: "Team management",
    image: "/ManagingTeam.png",
    head: "Managing Team",
    stack: "HTML",
    stack2: "CSS",
    stack3: "Javascript",
    parag: "A website built for a team Management firm",
    code: "https://github.com/iconicconcept",
    live: "https://iconicconcept.github.io/managing-team.io/",
  },
  // {
  //     id: "8",
  //     alt: "deesmart store",
  //     image: "../smart.png",
  //     head: "DeeSmart Store",
  //     stack: "HTML",stack2: "CSS",stack3: "Javascript",
  //     parag: "A mini E-commerce web application, dedicated to making sales less stressful",
  //     code: "https://github.com/iconicconcept",
  //     live: "https://iconicconcept.github.io/deesmart-store/"
  // }
];

export const featureCard = [
  {
    id: "1",
    head: "Full-Stack Development",
    parag: "Building Responsive and scalable full-stack application",
  },
  {
    id: "2",
    head: "Web Application",
    parag:
      "Building Responsible and user-friendly web applications with modern Technologies",
  },
  {
    id: "3",
    head: "Problem Solving",
    parag: "Building solutions dedicated to solve complex technical challenges",
  },
  {
    id: "4",
    head: "Quality Performance",
    parag: "Solutions with quality performance and solving dedicated problems",
  },
  {
    id: "5",
    head: "SEO",
    parag: "Scalable solutions with great SEO",
  },
];
